import type { Characteristics } from "./types"

export interface WfrpCareerSecondary {
  attacks: number
  wounds: number
  mag: number
}

export interface WfrpCareerData {
  type: "basic" | "advanced"
  role: string
  advances: Characteristics
  secondary: WfrpCareerSecondary
  entries: string[]
  exits: string[]
}

export const CAREER_DATA_ADVANCED: Record<string, WfrpCareerData> = {
  "Anointed Priest": {
    type: "advanced",
    role: "Priests",
    advances: { ws: 15, bs: 15, s: 10, t: 10, ag: 10, int: 15, wp: 25, fel: 20 },
    secondary: { attacks: 1, wounds: 5, mag: 2 },
    entries: ["Priest"],
    exits: ["Demagogue", "Flagellant", "High Priest", "Scholar", "Witch Hunter"],
  },
  "Artisan": {
    type: "advanced",
    role: "Peasants",
    advances: { ws: 0, bs: 0, s: 10, t: 10, ag: 20, int: 10, wp: 10, fel: 10 },
    secondary: { attacks: 0, wounds: 3, mag: 0 },
    entries: ["Engineer", "Militiaman", "Navigator", "Tradesman"],
    exits: ["Demagogue", "Engineer", "Guild Master", "Merchant", "Militiaman"],
  },
  "Assassin": {
    type: "advanced",
    role: "Warriors",
    advances: { ws: 25, bs: 25, s: 10, t: 10, ag: 30, int: 20, wp: 10, fel: 20 },
    secondary: { attacks: 2, wounds: 4, mag: 0 },
    entries: ["Champion", "Duellist", "Judicial Champion", "Outlaw Chief", "Spy", "Targeteer"],
    exits: ["Champion", "Outlaw Chief", "Rogue", "Sergeant", "Witch Hunter"],
  },
  "Captain": {
    type: "advanced",
    role: "Warriors",
    advances: { ws: 30, bs: 20, s: 20, t: 20, ag: 20, int: 15, wp: 15, fel: 25 },
    secondary: { attacks: 2, wounds: 7, mag: 0 },
    entries: ["Explorer", "Ghost Strider", "Knight", "Knight of the Inner Circle", "Noble Lord", "Outlaw Chief", "Sergeant", "Witch Hunter"],
    exits: ["Agitator", "Explorer", "Merchant", "Outlaw Chief", "Politician"],
  },
  "Cat Burglar": {
    type: "advanced",
    role: "Rogues",
    advances: { ws: 10, bs: 10, s: 5, t: 5, ag: 25, int: 10, wp: 10, fel: 0 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Bone Picker", "Charlatan", "Grave Robber", "Rat Catcher", "Thief"],
    exits: ["Crime Lord", "Fence", "Master Thief", "Racketeer", "Vagabond"],
  },
  "Champion": {
    type: "advanced",
    role: "Warriors",
    advances: { ws: 40, bs: 40, s: 25, t: 25, ag: 30, int: 0, wp: 20, fel: 0 },
    secondary: { attacks: 2, wounds: 8, mag: 0 },
    entries: ["Assassin", "Duellist", "Judicial Champion", "Knight of the Inner Circle", "Targeteer", "Veteran", "Witch Hunter"],
    exits: ["Assassin", "Scout", "Sergeant", "Witch Hunter"],
  },
  "Charlatan": {
    type: "advanced",
    role: "Rogues",
    advances: { ws: 10, bs: 10, s: 5, t: 10, ag: 15, int: 15, wp: 15, fel: 25 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Agitator", "Camp Follower", "Courtier", "Entertainer", "Envoy", "Fence", "Hedge Wizard", "Journeyman Wizard", "Minstrel", "Rogue", "Smuggler", "Thief"],
    exits: ["Cat Burglar", "Demagogue", "Outlaw", "Politician", "Spy"],
  },
  "Courtier": {
    type: "advanced",
    role: "Nobles",
    advances: { ws: 5, bs: 5, s: 0, t: 0, ag: 10, int: 20, wp: 20, fel: 20 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Noble", "Herald", "Pistolier", "Politician"],
    exits: ["Charlatan", "Duellist", "Noble Lord", "Politician", "Steward", "Spy"],
  },
  "Daemon Slayer": {
    type: "advanced",
    role: "Slayers",
    advances: { ws: 40, bs: 0, s: 30, t: 30, ag: 20, int: 0, wp: 30, fel: 0 },
    secondary: { attacks: 2, wounds: 8, mag: 0 },
    entries: ["Giant Slayer"],
    exits: ["Glorious death"],
  },
  "Demagogue": {
    type: "advanced",
    role: "Special",
    advances: { ws: 10, bs: 10, s: 0, t: 10, ag: 15, int: 20, wp: 15, fel: 30 },
    secondary: { attacks: 1, wounds: 4, mag: 0 },
    entries: ["Agitator", "Anointed Priest", "Artisan", "Charlatan", "Crime Lord", "Flagellant", "Friar", "Initiate", "Minstrel", "Outlaw", "Outlaw Chief", "Politician", "Rogue", "Vampire Hunter", "Witch Hunter"],
    exits: ["Crime Lord", "Friar", "Mercenary", "Outlaw Chief", "Politician"],
  },
  "Duellist": {
    type: "advanced",
    role: "Warriors",
    advances: { ws: 20, bs: 20, s: 10, t: 20, ag: 20, int: 15, wp: 15, fel: 10 },
    secondary: { attacks: 1, wounds: 4, mag: 0 },
    entries: ["Courtier", "Estalian Diestro", "Highwayman", "Pistolier", "Protagonist", "Sergeant", "Targeteer"],
    exits: ["Assassin", "Champion", "Highwayman", "Rogue", "Sergeant"],
  },
  "Engineer": {
    type: "advanced",
    role: "Academics",
    advances: { ws: 10, bs: 15, s: 5, t: 5, ag: 10, int: 20, wp: 10, fel: 0 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Artisan", "Miner", "Student", "Tradesman"],
    exits: ["Artisan", "Explorer", "Guild Master", "Pistolier", "Smuggler"],
  },
  "Explorer": {
    type: "advanced",
    role: "Rangers",
    advances: { ws: 20, bs: 20, s: 10, t: 15, ag: 15, int: 25, wp: 20, fel: 15 },
    secondary: { attacks: 1, wounds: 6, mag: 0 },
    entries: ["Captain", "Engineer", "Herald", "Master Thief", "Master Wizard", "Mate", "Navigator", "Scholar", "Scout", "Sea Captain", "Spy", "Wizard Lord"],
    exits: ["Captain", "Merchant", "Sea Captain", "Spy"],
  },
  "Fence": {
    type: "advanced",
    role: "Rogues",
    advances: { ws: 15, bs: 10, s: 10, t: 5, ag: 10, int: 5, wp: 10, fel: 10 },
    secondary: { attacks: 1, wounds: 4, mag: 0 },
    entries: ["Bone Picker", "Burgher", "Cat Burglar", "Grave Robber", "Innkeeper", "Racketeer", "Smuggler", "Steward", "Thief", "Tomb Robber"],
    exits: ["Charlatan", "Crime Lord", "Master Thief", "Racketeer"],
  },
  "Flagellant": {
    type: "advanced",
    role: "Priests",
    advances: { ws: 15, bs: 0, s: 10, t: 15, ag: 5, int: 0, wp: 20, fel: 10 },
    secondary: { attacks: 1, wounds: 6, mag: 0 },
    entries: ["Anointed Priest", "Friar", "Priest", "Zealot"],
    exits: ["Demagogue", "Interrogator", "Priest", "Soldier", "Veteran"],
  },
  "Friar": {
    type: "advanced",
    role: "Priests",
    advances: { ws: 10, bs: 0, s: 5, t: 10, ag: 0, int: 15, wp: 15, fel: 15 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Demagogue", "Initiate", "Physician", "Scholar", "Vagabond", "Zealot"],
    exits: ["Demagogue", "Flagellant", "Priest", "Scholar"],
  },
  "Ghost Strider": {
    type: "advanced",
    role: "Rangers",
    advances: { ws: 20, bs: 30, s: 15, t: 15, ag: 25, int: 20, wp: 20, fel: 0 },
    secondary: { attacks: 2, wounds: 6, mag: 0 },
    entries: ["Scout"],
    exits: ["Captain", "Outlaw Chief", "Targeteer", "Vampire Hunter"],
  },
  "Giant Slayer": {
    type: "advanced",
    role: "Slayers",
    advances: { ws: 25, bs: 0, s: 15, t: 15, ag: 10, int: 0, wp: 20, fel: 0 },
    secondary: { attacks: 1, wounds: 6, mag: 0 },
    entries: ["Troll Slayer"],
    exits: ["Daemon Slayer"],
  },
  "Guild Master": {
    type: "advanced",
    role: "Nobles",
    advances: { ws: 10, bs: 10, s: 0, t: 10, ag: 15, int: 30, wp: 20, fel: 35 },
    secondary: { attacks: 1, wounds: 5, mag: 0 },
    entries: ["Artisan", "Engineer", "Merchant", "Physician", "Wizard Lord"],
    exits: ["Crime Lord", "Politician", "Racketeer"],
  },
  "Herald": {
    type: "advanced",
    role: "Nobles",
    advances: { ws: 10, bs: 10, s: 5, t: 5, ag: 15, int: 15, wp: 10, fel: 20 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Messenger", "Valet"],
    exits: ["Agitator", "Courtier", "Entertainer", "Explorer", "Politician", "Squire"],
  },
  "High Priest": {
    type: "advanced",
    role: "Priests",
    advances: { ws: 20, bs: 20, s: 15, t: 15, ag: 15, int: 20, wp: 30, fel: 25 },
    secondary: { attacks: 1, wounds: 6, mag: 3 },
    entries: ["Anointed Priest"],
    exits: ["Politician", "Scholar", "Witch Hunter"],
  },
  "Highwayman": {
    type: "advanced",
    role: "Rogues",
    advances: { ws: 20, bs: 20, s: 10, t: 10, ag: 30, int: 20, wp: 15, fel: 25 },
    secondary: { attacks: 1, wounds: 4, mag: 0 },
    entries: ["Coachman", "Duellist", "Estalian Diestro", "Ferryman", "Minstrel", "Outlaw", "Outrider", "Roadwarden", "Toll Keeper"],
    exits: ["Agitator", "Duellist", "Master Thief", "Outlaw Chief", "Sergeant"],
  },
  "Innkeeper": {
    type: "advanced",
    role: "Peasants",
    advances: { ws: 10, bs: 5, s: 5, t: 10, ag: 20, int: 10, wp: 10, fel: 20 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Burgher", "Servant"],
    exits: ["Burgher", "Fence", "Merchant", "Outlaw", "Smuggler"],
  },
  "Interrogator": {
    type: "advanced",
    role: "Special",
    advances: { ws: 15, bs: 0, s: 20, t: 10, ag: 10, int: 10, wp: 20, fel: 15 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Barber-Surgeon", "Bodyguard", "Flagellant", "Jailer", "Thug"],
    exits: ["Physician", "Racketeer", "Thief"],
  },
  "Journeyman Wizard": {
    type: "advanced",
    role: "Academics",
    advances: { ws: 5, bs: 5, s: 0, t: 5, ag: 10, int: 20, wp: 25, fel: 10 },
    secondary: { attacks: 0, wounds: 3, mag: 2 },
    entries: ["Apprentice Wizard"],
    exits: ["Charlatan", "Master Wizard", "Scholar"],
  },
  "Judicial Champion": {
    type: "advanced",
    role: "Warriors",
    advances: { ws: 35, bs: 0, s: 15, t: 15, ag: 20, int: 10, wp: 15, fel: 0 },
    secondary: { attacks: 2, wounds: 6, mag: 0 },
    entries: ["Sergeant", "Veteran"],
    exits: ["Assassin", "Champion", "Sergeant", "Witch Hunter", "Zealot"],
  },
  "Knight": {
    type: "advanced",
    role: "Nobles",
    advances: { ws: 25, bs: 0, s: 15, t: 15, ag: 15, int: 5, wp: 15, fel: 5 },
    secondary: { attacks: 1, wounds: 4, mag: 0 },
    entries: ["Noble Lord", "Pistolier", "Sergeant", "Squire", "Vampire Hunter"],
    exits: ["Captain", "Initiate", "Knight of the Inner Circle", "Noble Lord", "Vampire Hunter"],
  },
  "Knight of the Inner Circle": {
    type: "advanced",
    role: "Nobles",
    advances: { ws: 35, bs: 10, s: 20, t: 20, ag: 20, int: 15, wp: 25, fel: 15 },
    secondary: { attacks: 2, wounds: 8, mag: 0 },
    entries: ["Knight", "Witch Hunter"],
    exits: ["Captain", "Champion", "Noble Lord", "Witch Hunter"],
  },
  "Master Thief": {
    type: "advanced",
    role: "Rogues",
    advances: { ws: 20, bs: 20, s: 10, t: 10, ag: 40, int: 25, wp: 20, fel: 25 },
    secondary: { attacks: 1, wounds: 6, mag: 0 },
    entries: ["Cat Burglar", "Crime Lord", "Fence", "Highwayman", "Racketeer", "Spy"],
    exits: ["Crime Lord", "Explorer", "Outlaw Chief", "Targeteer"],
  },
  "Master Wizard": {
    type: "advanced",
    role: "Academics",
    advances: { ws: 10, bs: 10, s: 0, t: 10, ag: 15, int: 30, wp: 35, fel: 15 },
    secondary: { attacks: 0, wounds: 4, mag: 3 },
    entries: ["Journeyman Wizard"],
    exits: ["Explorer", "Scholar", "Wizard Lord"],
  },
  "Mate": {
    type: "advanced",
    role: "Warriors",
    advances: { ws: 15, bs: 15, s: 10, t: 15, ag: 10, int: 10, wp: 10, fel: 10 },
    secondary: { attacks: 1, wounds: 4, mag: 0 },
    entries: ["Marine", "Seaman"],
    exits: ["Explorer", "Merchant", "Navigator", "Sea Captain"],
  },
  "Merchant": {
    type: "advanced",
    role: "Peasants",
    advances: { ws: 10, bs: 10, s: 5, t: 5, ag: 10, int: 25, wp: 20, fel: 20 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Artisan", "Burgher", "Captain", "Envoy", "Explorer", "Fisherman", "Innkeeper", "Mate", "Scholar", "Steward", "Tradesman"],
    exits: ["Guild Master", "Militiaman", "Politician", "Racketeer", "Spy"],
  },
  "Minstrel": {
    type: "advanced",
    role: "Rogues",
    advances: { ws: 10, bs: 10, s: 0, t: 0, ag: 15, int: 10, wp: 5, fel: 25 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Entertainer"],
    exits: ["Charlatan", "Demagogue", "Highwayman", "Spy", "Student"],
  },
  "Navigator": {
    type: "advanced",
    role: "Special",
    advances: { ws: 10, bs: 10, s: 5, t: 5, ag: 10, int: 25, wp: 10, fel: 5 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Boatman", "Fisherman", "Mate", "Scribe", "Seaman"],
    exits: ["Artisan", "Explorer", "Scholar", "Sea Captain"],
  },
  "Noble Lord": {
    type: "advanced",
    role: "Nobles",
    advances: { ws: 25, bs: 15, s: 10, t: 10, ag: 10, int: 20, wp: 20, fel: 30 },
    secondary: { attacks: 1, wounds: 6, mag: 0 },
    entries: ["Courtier", "Knight", "Knight of the Inner Circle", "Politician", "Sea Captain"],
    exits: ["Captain", "Knight", "Scholar", "Sea Captain"],
  },
  "Outlaw Chief": {
    type: "advanced",
    role: "Rogues",
    advances: { ws: 20, bs: 30, s: 10, t: 20, ag: 10, int: 10, wp: 10, fel: 20 },
    secondary: { attacks: 2, wounds: 6, mag: 0 },
    entries: ["Crime Lord", "Demagogue", "Ghost Strider", "Highwayman", "Master Thief", "Racketeer", "Scout", "Veteran"],
    exits: ["Assassin", "Captain", "Crime Lord", "Demagogue"],
  },
  "Physician": {
    type: "advanced",
    role: "Academics",
    advances: { ws: 0, bs: 0, s: 10, t: 10, ag: 15, int: 30, wp: 20, fel: 15 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Barber-Surgeon", "Interrogator", "Scholar", "Student"],
    exits: ["Friar", "Guild Master", "Scholar", "Spy"],
  },
  "Pistolier": {
    type: "advanced",
    role: "Nobles",
    advances: { ws: 20, bs: 20, s: 10, t: 10, ag: 15, int: 0, wp: 15, fel: 15 },
    secondary: { attacks: 1, wounds: 4, mag: 0 },
    entries: ["Engineer", "Noble"],
    exits: ["Courtier", "Duellist", "Knight", "Sergeant", "Veteran"],
  },
  "Politician": {
    type: "advanced",
    role: "Nobles",
    advances: { ws: 5, bs: 5, s: 5, t: 10, ag: 0, int: 20, wp: 10, fel: 20 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Agitator", "Bailiff", "Captain", "Charlatan", "Courtier", "Crime Lord", "Demagogue", "Guild Master", "Herald", "High Priest", "Merchant", "Noble", "Peasant", "Racketeer", "Toll Keeper"],
    exits: ["Courtier", "Crime Lord", "Demagogue", "Noble Lord", "Racketeer", "Steward"],
  },
  "Priest": {
    type: "advanced",
    role: "Priests",
    advances: { ws: 10, bs: 10, s: 5, t: 10, ag: 5, int: 10, wp: 20, fel: 15 },
    secondary: { attacks: 0, wounds: 4, mag: 1 },
    entries: ["Flagellant", "Friar", "Initiate"],
    exits: ["Anointed Priest", "Flagellant", "Scholar", "Steward"],
  },
  "Racketeer": {
    type: "advanced",
    role: "Rogues",
    advances: { ws: 20, bs: 15, s: 15, t: 10, ag: 10, int: 0, wp: 15, fel: 10 },
    secondary: { attacks: 1, wounds: 5, mag: 0 },
    entries: ["Bailiff", "Bodyguard", "Cat Burglar", "Fence", "Guild Master", "Interrogator", "Merchant", "Politician", "Protagonist", "Spy", "Thug"],
    exits: ["Fence", "Master Thief", "Politician", "Outlaw Chief"],
  },
  "Scholar": {
    type: "advanced",
    role: "Academics",
    advances: { ws: 5, bs: 5, s: 5, t: 5, ag: 10, int: 30, wp: 15, fel: 15 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Anointed Priest", "Apprentice Wizard", "Friar", "High Priest", "Journeyman Wizard", "Master Wizard", "Navigator", "Noble Lord", "Physician", "Priest", "Scribe", "Sea Captain", "Student"],
    exits: ["Apprentice Wizard", "Explorer", "Friar", "Merchant", "Physician", "Steward"],
  },
  "Scout": {
    type: "advanced",
    role: "Rangers",
    advances: { ws: 20, bs: 20, s: 10, t: 10, ag: 15, int: 20, wp: 15, fel: 0 },
    secondary: { attacks: 1, wounds: 6, mag: 0 },
    entries: ["Bounty Hunter", "Champion", "Charcoal-Burner", "Coachman", "Fieldwarden", "Hunter", "Kithband Warrior", "Messenger", "Miner", "Outrider", "Roadwarden", "Runebearer", "Vagabond", "Woodsman"],
    exits: ["Explorer", "Outlaw Chief", "Sergeant", "Vampire Hunter", "Ghost Strider"],
  },
  "Sea Captain": {
    type: "advanced",
    role: "Special",
    advances: { ws: 25, bs: 20, s: 15, t: 20, ag: 20, int: 20, wp: 25, fel: 30 },
    secondary: { attacks: 2, wounds: 6, mag: 0 },
    entries: ["Explorer", "Mate", "Navigator", "Noble Lord"],
    exits: ["Explorer", "Noble Lord", "Scholar", "Spy"],
  },
  "Sergeant": {
    type: "advanced",
    role: "Warriors",
    advances: { ws: 20, bs: 15, s: 10, t: 10, ag: 10, int: 10, wp: 10, fel: 20 },
    secondary: { attacks: 1, wounds: 4, mag: 0 },
    entries: ["Assassin", "Champion", "Duellist", "Highwayman", "Judicial Champion", "Kislevite Kossar", "Marine", "Mercenary", "Militiaman", "Norse Berserker", "Pistolier", "Roadwarden", "Scout", "Shieldbreaker", "Soldier", "Squire", "Targeteer", "Veteran", "Watchman"],
    exits: ["Captain", "Duellist", "Judicial Champion", "Knight"],
  },
  "Spy": {
    type: "advanced",
    role: "Rogues",
    advances: { ws: 15, bs: 15, s: 5, t: 10, ag: 20, int: 20, wp: 35, fel: 20 },
    secondary: { attacks: 1, wounds: 4, mag: 0 },
    entries: ["Camp Follower", "Charlatan", "Courtier", "Explorer", "Merchant", "Minstrel", "Physician", "Sea Captain", "Servant"],
    exits: ["Assassin", "Explorer", "Master Thief", "Racketeer"],
  },
  "Steward": {
    type: "advanced",
    role: "Nobles",
    advances: { ws: 10, bs: 10, s: 10, t: 10, ag: 0, int: 30, wp: 20, fel: 25 },
    secondary: { attacks: 0, wounds: 4, mag: 0 },
    entries: ["Courtier", "Politician", "Priest", "Scholar", "Valet"],
    exits: ["Crime Lord", "Fence", "Merchant", "Noble"],
  },
  "Targeteer": {
    type: "advanced",
    role: "Warriors",
    advances: { ws: 0, bs: 35, s: 10, t: 10, ag: 25, int: 10, wp: 20, fel: 15 },
    secondary: { attacks: 1, wounds: 4, mag: 0 },
    entries: ["Bounty Hunter", "Hunter", "Ghost Strider", "Master Thief", "Vampire Hunter", "Veteran"],
    exits: ["Assassin", "Champion", "Duellist", "Sergeant"],
  },
  "Vampire Hunter": {
    type: "advanced",
    role: "Special",
    advances: { ws: 20, bs: 20, s: 10, t: 20, ag: 15, int: 15, wp: 20, fel: 0 },
    secondary: { attacks: 1, wounds: 4, mag: 0 },
    entries: ["Bounty Hunter", "Field Warden", "Ghost Strider", "Knight", "Scout", "Tomb Robber"],
    exits: ["Demagogue", "Initiate", "Knight", "Targeteer", "Witch Hunter"],
  },
  "Veteran": {
    type: "advanced",
    role: "Warriors",
    advances: { ws: 20, bs: 20, s: 10, t: 10, ag: 15, int: 0, wp: 15, fel: 0 },
    secondary: { attacks: 1, wounds: 6, mag: 0 },
    entries: ["Flagellant", "Kislevite Kossar", "Kithband Warrior", "Mercenary", "Norse Berserker", "Outlaw", "Pistolier", "Pit Fighter", "Runebearer", "Shieldbreaker", "Soldier", "Squire"],
    exits: ["Champion", "Judicial Champion", "Outlaw Chief", "Sergeant", "Targeteer"],
  },
  "Witch Hunter": {
    type: "advanced",
    role: "Special",
    advances: { ws: 30, bs: 30, s: 15, t: 15, ag: 15, int: 15, wp: 35, fel: 20 },
    secondary: { attacks: 2, wounds: 6, mag: 0 },
    entries: ["Anointed Priest", "Assassin", "Champion", "High Priest", "Judicial Champion", "Knight of the Inner Circle", "Vampire Hunter"],
    exits: ["Captain", "Champion", "Demagogue", "Initiate", "Knight of the Inner Circle"],
  },
  "Wizard Lord": {
    type: "advanced",
    role: "Academics",
    advances: { ws: 15, bs: 15, s: 5, t: 15, ag: 20, int: 35, wp: 40, fel: 20 },
    secondary: { attacks: 0, wounds: 5, mag: 4 },
    entries: ["Master Wizard"],
    exits: ["Explorer", "Guild Master"],
  },
}
