import type { Characteristics } from "./types"

export interface WfrpCareerSecondary {
  attacks: number
  wounds: number
  mag: number
}

export interface WfrpCareerData {
  type: "basic" | "advanced"
  role: string
  advances: Characteristics
  secondary: WfrpCareerSecondary
  entries: string[]
  exits: string[]
}

export const CAREER_DATA_BASIC: Record<string, WfrpCareerData> = {
  "Agitator": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 5, bs: 5, s: 0, t: 0, ag: 5, int: 10, wp: 0, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Burgher", "Captain", "Herald", "Highwayman", "Scribe", "Servant", "Student", "Zealot"],
    exits: ["Charlatan", "Demagogue", "Outlaw", "Politician", "Rogue", "Zealot"],
  },
  "Apprentice Wizard": {
    type: "basic",
    role: "Academics",
    advances: { ws: 0, bs: 0, s: 0, t: 0, ag: 5, int: 10, wp: 15, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 1 },
    entries: ["Hedge Wizard", "Scholar", "Scribe", "Student"],
    exits: ["Journeyman Wizard", "Scholar", "Scribe"],
  },
  "Bailiff": {
    type: "basic",
    role: "Peasants",
    advances: { ws: 5, bs: 5, s: 5, t: 0, ag: 0, int: 10, wp: 5, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Bodyguard", "Jailer"],
    exits: ["Militiaman", "Politician", "Protagonist", "Racketeer", "Smuggler", "Toll Keeper"],
  },
  "Barber-Surgeon": {
    type: "basic",
    role: "Peasants",
    advances: { ws: 5, bs: 0, s: 0, t: 0, ag: 10, int: 10, wp: 10, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Initiate", "Student"],
    exits: ["Interrogator", "Grave Robber", "Physician", "Tradesman", "Vagabond"],
  },
  "Boatman": {
    type: "basic",
    role: "Rangers",
    advances: { ws: 10, bs: 5, s: 5, t: 5, ag: 10, int: 5, wp: 0, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Ferryman", "Smuggler"],
    exits: ["Fisherman", "Marine", "Navigator", "Seaman", "Smuggler"],
  },
  "Bodyguard": {
    type: "basic",
    role: "Warriors",
    advances: { ws: 10, bs: 0, s: 5, t: 5, ag: 5, int: 0, wp: 0, fel: 0 },
    secondary: { attacks: 1, wounds: 3, mag: 0 },
    entries: ["Estalian Diestro", "Jailer", "Mercenary", "Thug"],
    exits: ["Bailiff", "Bounty Hunter", "Interrogator", "Jailer", "Mercenary", "Protagonist", "Racketeer"],
  },
  "Bone Picker": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 5, bs: 0, s: 5, t: 10, ag: 5, int: 0, wp: 5, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Peasant", "Rat Catcher", "Vagabond"],
    exits: ["Camp Follower", "Cat Burglar", "Fence", "Grave Robber", "Smuggler"],
  },
  "Bounty Hunter": {
    type: "basic",
    role: "Warriors",
    advances: { ws: 5, bs: 10, s: 5, t: 0, ag: 10, int: 0, wp: 5, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Bodyguard", "Fieldwarden", "Hunter", "Kislevite Kossar", "Mercenary", "Pit Fighter"],
    exits: ["Mercenary", "Protagonist", "Scout", "Targeteer", "Vampire Hunter"],
  },
  "Burgher": {
    type: "basic",
    role: "Peasants",
    advances: { ws: 5, bs: 0, s: 0, t: 0, ag: 5, int: 10, wp: 5, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Innkeeper", "Servant"],
    exits: ["Agitator", "Fence", "Innkeeper", "Merchant", "Militiaman", "Tradesman", "Valet"],
  },
  "Camp Follower": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 0, bs: 0, s: 0, t: 5, ag: 10, int: 5, wp: 5, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Bone Picker", "Servant"],
    exits: ["Charcoal-Burner", "Charlatan", "Servant", "Smuggler", "Spy", "Tradesman", "Vagabond"],
  },
  "Charcoal-Burner": {
    type: "basic",
    role: "Peasants",
    advances: { ws: 5, bs: 0, s: 5, t: 5, ag: 5, int: 5, wp: 5, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Camp Follower", "Hunter", "Miner", "Peasant"],
    exits: ["Hunter", "Miner", "Scout", "Vagabond", "Woodsman"],
  },
  "Coachman": {
    type: "basic",
    role: "Rangers",
    advances: { ws: 5, bs: 10, s: 0, t: 0, ag: 10, int: 0, wp: 5, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Outrider", "Messenger"],
    exits: ["Ferryman", "Highwayman", "Outlaw", "Roadwarden", "Scout", "Smuggler", "Toll Keeper"],
  },
  "Entertainer": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 5, bs: 10, s: 0, t: 0, ag: 10, int: 0, wp: 5, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Herald", "Rogue", "Thief", "Vagabond"],
    exits: ["Charlatan", "Minstrel", "Rogue", "Thief", "Vagabond"],
  },
  "Envoy": {
    type: "basic",
    role: "Peasants",
    advances: { ws: 5, bs: 5, s: 0, t: 0, ag: 5, int: 10, wp: 5, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Student", "Tradesman"],
    exits: ["Charlatan", "Merchant", "Rogue", "Seaman", "Student", "Vagabond"],
  },
  "Estalian Diestro": {
    type: "basic",
    role: "Warriors",
    advances: { ws: 15, bs: 0, s: 5, t: 5, ag: 10, int: 5, wp: 0, fel: 0 },
    secondary: { attacks: 1, wounds: 2, mag: 0 },
    entries: [],
    exits: ["Bodyguard", "Duellist", "Highwayman", "Protagonist", "Rogue"],
  },
  "Ferryman": {
    type: "basic",
    role: "Peasants",
    advances: { ws: 5, bs: 5, s: 10, t: 5, ag: 5, int: 5, wp: 0, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Coachman", "Smuggler", "Toll Keeper"],
    exits: ["Boatman", "Highwayman", "Roadwarden", "Seaman", "Smuggler"],
  },
  "Fieldwarden": {
    type: "basic",
    role: "Rangers",
    advances: { ws: 5, bs: 10, s: 0, t: 5, ag: 10, int: 0, wp: 10, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Hunter", "Militiaman", "Toll Keeper"],
    exits: ["Bounty Hunter", "Mercenary", "Scout", "Vagabond", "Vampire Hunter"],
  },
  "Fisherman": {
    type: "basic",
    role: "Rangers",
    advances: { ws: 0, bs: 5, s: 10, t: 5, ag: 10, int: 5, wp: 0, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Boatman", "Peasant"],
    exits: ["Marine", "Merchant", "Militiaman", "Navigator", "Seaman"],
  },
  "Grave Robber": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 5, bs: 5, s: 5, t: 0, ag: 10, int: 0, wp: 10, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Barber-Surgeon", "Bone Picker", "Rat Catcher"],
    exits: ["Cat Burglar", "Fence", "Rat Catcher", "Student", "Thief"],
  },
  "Hedge Wizard": {
    type: "basic",
    role: "Academics",
    advances: { ws: 0, bs: 0, s: 0, t: 5, ag: 5, int: 5, wp: 10, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 1 },
    entries: [],
    exits: ["Apprentice Wizard", "Charlatan", "Initiate", "Outlaw", "Vagabond"],
  },
  "Hunter": {
    type: "basic",
    role: "Rangers",
    advances: { ws: 0, bs: 15, s: 0, t: 5, ag: 10, int: 5, wp: 0, fel: 0 },
    secondary: { attacks: 0, wounds: 3, mag: 0 },
    entries: ["Charcoal-Burner", "Kithband Warrior", "Woodsman"],
    exits: ["Bounty Hunter", "Charcoal-Burner", "Fieldwarden", "Kithband Warrior", "Miner", "Scout", "Soldier", "Targeteer"],
  },
  "Initiate": {
    type: "basic",
    role: "Priests",
    advances: { ws: 5, bs: 5, s: 0, t: 5, ag: 0, int: 10, wp: 10, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Hedge Wizard", "Knight", "Scribe", "Student", "Vampire Hunter", "Witch Hunter", "Zealot"],
    exits: ["Barber-Surgeon", "Demagogue", "Friar", "Priest", "Scribe", "Zealot"],
  },
  "Jailer": {
    type: "basic",
    role: "Special",
    advances: { ws: 10, bs: 0, s: 10, t: 10, ag: 0, int: 0, wp: 5, fel: 0 },
    secondary: { attacks: 0, wounds: 3, mag: 0 },
    entries: ["Bodyguard", "Rat Catcher"],
    exits: ["Bailiff", "Bodyguard", "Interrogator", "Rat Catcher", "Watchman"],
  },
  "Kislevite Kossar": {
    type: "basic",
    role: "Warriors",
    advances: { ws: 10, bs: 10, s: 0, t: 10, ag: 0, int: 0, wp: 10, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: [],
    exits: ["Bounty Hunter", "Mercenary", "Sergeant", "Shieldbreaker", "Veteran"],
  },
  "Kithband Warrior": {
    type: "basic",
    role: "Rangers",
    advances: { ws: 5, bs: 5, s: 0, t: 0, ag: 10, int: 10, wp: 5, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Hunter", "Messenger"],
    exits: ["Hunter", "Outrider", "Scout", "Vagabond", "Veteran"],
  },
  "Marine": {
    type: "basic",
    role: "Warriors",
    advances: { ws: 10, bs: 10, s: 10, t: 0, ag: 5, int: 0, wp: 5, fel: 0 },
    secondary: { attacks: 1, wounds: 3, mag: 0 },
    entries: ["Boatman", "Fisherman", "Seaman"],
    exits: ["Mate", "Outlaw", "Sergeant", "Smuggler", "Thug"],
  },
  "Mercenary": {
    type: "basic",
    role: "Warriors",
    advances: { ws: 10, bs: 10, s: 5, t: 5, ag: 5, int: 0, wp: 5, fel: 0 },
    secondary: { attacks: 1, wounds: 2, mag: 0 },
    entries: ["Bodyguard", "Bounty Hunter", "Demagogue", "Fieldwarden", "Kislevite Kossar", "Militiaman", "Miner", "Norse Berserker", "Outrider", "Pit Fighter", "Soldier", "Thug", "Watchman"],
    exits: ["Bodyguard", "Bounty Hunter", "Outlaw", "Sergeant", "Shieldbreaker", "Veteran"],
  },
  "Messenger": {
    type: "basic",
    role: "Rangers",
    advances: { ws: 5, bs: 5, s: 0, t: 5, ag: 10, int: 5, wp: 5, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Militiaman", "Roadwarden", "Servant"],
    exits: ["Coachman", "Herald", "Kithband Warrior", "Outrider", "Roadwarden", "Scout", "Soldier"],
  },
  "Militiaman": {
    type: "basic",
    role: "Peasants",
    advances: { ws: 10, bs: 5, s: 5, t: 5, ag: 10, int: 0, wp: 0, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Artisan", "Bailiff", "Burgher", "Fisherman", "Merchant", "Peasant", "Tradesman", "Woodsman"],
    exits: ["Artisan", "Fieldwarden", "Mercenary", "Messenger", "Outlaw", "Sergeant", "Thief"],
  },
  "Miner": {
    type: "basic",
    role: "Peasants",
    advances: { ws: 5, bs: 5, s: 10, t: 5, ag: 0, int: 5, wp: 5, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Charcoal-Burner", "Hunter"],
    exits: ["Charcoal-Burner", "Engineer", "Mercenary", "Scout", "Shieldbreaker", "Smuggler"],
  },
  "Noble": {
    type: "basic",
    role: "Nobles",
    advances: { ws: 10, bs: 5, s: 0, t: 0, ag: 5, int: 5, wp: 5, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Squire", "Steward"],
    exits: ["Courtier", "Pistolier", "Politician", "Rogue", "Squire", "Student"],
  },
  "Norse Berserker": {
    type: "basic",
    role: "Warriors",
    advances: { ws: 15, bs: 0, s: 10, t: 10, ag: 0, int: 0, wp: 10, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: [],
    exits: ["Mercenary", "Pit Fighter", "Seaman", "Sergeant", "Veteran"],
  },
  "Outlaw": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 10, bs: 10, s: 0, t: 0, ag: 10, int: 5, wp: 0, fel: 0 },
    secondary: { attacks: 1, wounds: 2, mag: 0 },
    entries: ["Agitator", "Charlatan", "Coachman", "Hedge Wizard", "Innkeeper", "Marine", "Mercenary", "Militiaman", "Peasant", "Roadwarden", "Rogue", "Squire", "Toll Keeper", "Woodsman", "Zealot"],
    exits: ["Demagogue", "Highwayman", "Thief", "Vagabond", "Veteran"],
  },
  "Outrider": {
    type: "basic",
    role: "Rangers",
    advances: { ws: 5, bs: 10, s: 0, t: 0, ag: 10, int: 10, wp: 5, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Kithband Warrior", "Messenger", "Roadwarden", "Soldier"],
    exits: ["Coachman", "Highwayman", "Mercenary", "Roadwarden", "Scout"],
  },
  "Peasant": {
    type: "basic",
    role: "Peasants",
    advances: { ws: 5, bs: 5, s: 5, t: 10, ag: 5, int: 0, wp: 5, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: [],
    exits: ["Bone Picker", "Charcoal-Burner", "Fisherman", "Militiaman", "Outlaw", "Politician", "Servant", "Tradesman", "Zealot"],
  },
  "Pit Fighter": {
    type: "basic",
    role: "Warriors",
    advances: { ws: 15, bs: 0, s: 0, t: 10, ag: 10, int: 0, wp: 10, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Norse Berserker", "Protagonist", "Shieldbreaker", "Thug"],
    exits: ["Bounty Hunter", "Mercenary", "Protagonist", "Troll Slayer", "Veteran"],
  },
  "Protagonist": {
    type: "basic",
    role: "Warriors",
    advances: { ws: 10, bs: 0, s: 10, t: 0, ag: 10, int: 0, wp: 10, fel: 0 },
    secondary: { attacks: 1, wounds: 2, mag: 0 },
    entries: ["Bailiff", "Bodyguard", "Bounty Hunter", "Estalian Diestro", "Pit Fighter"],
    exits: ["Duellist", "Pit Fighter", "Racketeer", "Thief", "Thug"],
  },
  "Rat Catcher": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 5, bs: 10, s: 0, t: 5, ag: 10, int: 0, wp: 10, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Grave Robber", "Jailer", "Runebearer", "Tomb Robber"],
    exits: ["Bone Picker", "Cat Burglar", "Grave Robber", "Jailer", "Shieldbreaker", "Thief"],
  },
  "Roadwarden": {
    type: "basic",
    role: "Rangers",
    advances: { ws: 10, bs: 10, s: 5, t: 0, ag: 10, int: 5, wp: 5, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Coachman", "Ferryman", "Messenger", "Outrider", "Watchman"],
    exits: ["Highwayman", "Messenger", "Outlaw", "Outrider", "Scout", "Sergeant", "Toll Keeper"],
  },
  "Rogue": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 5, bs: 5, s: 0, t: 0, ag: 10, int: 5, wp: 5, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Agitator", "Assassin", "Duellist", "Entertainer", "Envoy", "Estalian Diestro", "Noble", "Seaman", "Thief", "Valet"],
    exits: ["Charlatan", "Demagogue", "Entertainer", "Outlaw", "Servant", "Thief"],
  },
  "Runebearer": {
    type: "basic",
    role: "Rangers",
    advances: { ws: 10, bs: 0, s: 5, t: 5, ag: 10, int: 5, wp: 5, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Shieldbreaker"],
    exits: ["Rat Catcher", "Scout", "Shieldbreaker", "Tomb Robber", "Veteran"],
  },
  "Scribe": {
    type: "basic",
    role: "Academics",
    advances: { ws: 0, bs: 0, s: 0, t: 0, ag: 10, int: 10, wp: 10, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Apprentice Wizard", "Initiate"],
    exits: ["Agitator", "Apprentice Wizard", "Initiate", "Navigator", "Scholar"],
  },
  "Seaman": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 10, bs: 5, s: 10, t: 0, ag: 10, int: 0, wp: 0, fel: 0 },
    secondary: { attacks: 1, wounds: 2, mag: 0 },
    entries: ["Boatman", "Envoy", "Ferryman", "Fisherman", "Norse Berserker", "Smuggler"],
    exits: ["Marine", "Mate", "Navigator", "Rogue", "Smuggler"],
  },
  "Servant": {
    type: "basic",
    role: "Nobles",
    advances: { ws: 5, bs: 0, s: 5, t: 0, ag: 10, int: 5, wp: 10, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Camp Follower", "Peasant", "Rogue"],
    exits: ["Agitator", "Burgher", "Camp Follower", "Innkeeper", "Messenger", "Spy", "Thief", "Valet"],
  },
  "Shieldbreaker": {
    type: "basic",
    role: "Warriors",
    advances: { ws: 10, bs: 0, s: 5, t: 5, ag: 10, int: 0, wp: 5, fel: 0 },
    secondary: { attacks: 1, wounds: 2, mag: 0 },
    entries: ["Kislevite Kossar", "Mercenary", "Miner", "Rat Catcher", "Runebearer", "Smuggler", "Tomb Robber"],
    exits: ["Pit Fighter", "Runebearer", "Sergeant", "Smuggler", "Tomb Robber", "Veteran"],
  },
  "Smuggler": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 5, bs: 5, s: 0, t: 0, ag: 10, int: 10, wp: 0, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Bailiff", "Boatman", "Bone Picker", "Camp Follower", "Coachman", "Engineer", "Ferryman", "Innkeeper", "Marine", "Miner", "Seaman", "Shieldbreaker"],
    exits: ["Boatman", "Charlatan", "Fence", "Ferryman", "Seaman", "Shieldbreaker", "Thief"],
  },
  "Soldier": {
    type: "basic",
    role: "Warriors",
    advances: { ws: 10, bs: 10, s: 0, t: 0, ag: 10, int: 0, wp: 5, fel: 0 },
    secondary: { attacks: 1, wounds: 2, mag: 0 },
    entries: ["Flagellant", "Hunter", "Messenger", "Toll Keeper", "Watchman"],
    exits: ["Mercenary", "Outrider", "Sergeant", "Vagabond", "Veteran", "Watchman"],
  },
  "Squire": {
    type: "basic",
    role: "Nobles",
    advances: { ws: 10, bs: 5, s: 5, t: 5, ag: 5, int: 0, wp: 0, fel: 5 },
    secondary: { attacks: 1, wounds: 2, mag: 0 },
    entries: ["Herald", "Noble", "Valet"],
    exits: ["Knight", "Noble", "Outlaw", "Sergeant", "Veteran"],
  },
  "Student": {
    type: "basic",
    role: "Academics",
    advances: { ws: 0, bs: 0, s: 0, t: 0, ag: 10, int: 10, wp: 5, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Envoy", "Grave Robber", "Minstrel", "Noble", "Valet"],
    exits: ["Agitator", "Apprentice Wizard", "Barber-Surgeon", "Engineer", "Envoy", "Initiate", "Physician", "Scholar"],
  },
  "Thief": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 5, bs: 5, s: 0, t: 0, ag: 15, int: 5, wp: 0, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Entertainer", "Grave Robber", "Interrogator", "Militiaman", "Outlaw", "Protagonist", "Rat Catcher", "Rogue", "Servant", "Smuggler", "Toll Keeper", "Tomb Robber", "Vagabond"],
    exits: ["Cat Burglar", "Charlatan", "Entertainer", "Fence", "Rogue", "Tomb Robber"],
  },
  "Thug": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 10, bs: 0, s: 5, t: 5, ag: 0, int: 0, wp: 5, fel: 5 },
    secondary: { attacks: 1, wounds: 2, mag: 0 },
    entries: ["Marine", "Protagonist"],
    exits: ["Bodyguard", "Interrogator", "Mercenary", "Pit Fighter", "Racketeer"],
  },
  "Toll Keeper": {
    type: "basic",
    role: "Special",
    advances: { ws: 10, bs: 5, s: 5, t: 10, ag: 5, int: 0, wp: 5, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Bailiff", "Coachman", "Roadwarden"],
    exits: ["Ferryman", "Fieldwarden", "Highwayman", "Outlaw", "Soldier", "Politician", "Thief"],
  },
  "Tomb Robber": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 10, bs: 0, s: 0, t: 0, ag: 10, int: 10, wp: 10, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Runebearer", "Shieldbreaker", "Thief"],
    exits: ["Fence", "Rat Catcher", "Shieldbreaker", "Thief", "Vampire Hunter"],
  },
  "Tradesman": {
    type: "basic",
    role: "Peasants",
    advances: { ws: 0, bs: 0, s: 5, t: 5, ag: 10, int: 5, wp: 10, fel: 0 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Barber-Surgeon", "Burgher", "Camp Follower", "Peasant", "Watchman"],
    exits: ["Artisan", "Engineer", "Envoy", "Merchant", "Militiaman", "Zealot"],
  },
  "Troll Slayer": {
    type: "basic",
    role: "Slayers",
    advances: { ws: 10, bs: 0, s: 5, t: 5, ag: 5, int: 0, wp: 10, fel: 0 },
    secondary: { attacks: 1, wounds: 3, mag: 0 },
    entries: ["Pit Fighter"],
    exits: ["Giant Slayer"],
  },
  "Vagabond": {
    type: "basic",
    role: "Rogues",
    advances: { ws: 5, bs: 10, s: 0, t: 0, ag: 10, int: 5, wp: 0, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Barber-Surgeon", "Camp Follower", "Cat Burglar", "Charcoal-Burner", "Entertainer", "Envoy", "Fieldwarden", "Hedge Wizard", "Kithband Warrior", "Outlaw", "Soldier", "Woodsman"],
    exits: ["Bone Picker", "Entertainer", "Friar", "Scout", "Thief", "Woodsman"],
  },
  "Valet": {
    type: "basic",
    role: "Nobles",
    advances: { ws: 0, bs: 0, s: 0, t: 0, ag: 10, int: 10, wp: 5, fel: 10 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Burgher", "Servant"],
    exits: ["Herald", "Rogue", "Squire", "Steward", "Student"],
  },
  "Watchman": {
    type: "basic",
    role: "Peasants",
    advances: { ws: 10, bs: 5, s: 5, t: 0, ag: 5, int: 10, wp: 0, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Jailer", "Soldier"],
    exits: ["Mercenary", "Racketeer", "Roadwarden", "Sergeant", "Soldier", "Tradesman"],
  },
  "Woodsman": {
    type: "basic",
    role: "Rangers",
    advances: { ws: 10, bs: 0, s: 10, t: 0, ag: 5, int: 0, wp: 10, fel: 0 },
    secondary: { attacks: 0, wounds: 3, mag: 0 },
    entries: ["Charcoal-Burner", "Vagabond"],
    exits: ["Hunter", "Militiaman", "Outlaw", "Scout", "Vagabond"],
  },
  "Zealot": {
    type: "basic",
    role: "Priests",
    advances: { ws: 10, bs: 0, s: 5, t: 10, ag: 0, int: 0, wp: 10, fel: 5 },
    secondary: { attacks: 0, wounds: 2, mag: 0 },
    entries: ["Agitator", "Initiate", "Judicial Champion", "Peasant", "Tradesman"],
    exits: ["Agitator", "Initiate", "Flagellant", "Friar", "Outlaw"],
  },
}
